# Generated by Django 5.1.5 on 2025-02-03 14:30

import datetime
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=32)),
                ("last_name", models.CharField(max_length=32)),
                ("hired", models.DateField()),
                ("qualifications", models.TextField()),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="ClassRoom",
            fields=[
                (
                    "room_number",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("seats", models.IntegerField()),
                ("beamer", models.BooleanField(default=False)),
                (
                    "lab",
                    models.IntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "No"),
                            (2, "Biology"),
                            (3, "Chemistry"),
                            (4, "Physics"),
                            (5, "Geography"),
                            (5, "Mathematics"),
                            (6, "Visual arts"),
                            (7, "Music"),
                            (8, "Other"),
                        ],
                        default=0,
                    ),
                ),
            ],
            options={
                "ordering": ["room_number"],
                "indexes": [
                    models.Index(
                        fields=["room_number"], name="schooldata__room_nu_c5c677_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("seats__gt", 0)), name="seats_gt_zero"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("first_name", models.CharField(max_length=32)),
                ("last_name", models.CharField(max_length=32)),
                ("date_of_birth", models.DateField()),
                ("gpa", models.DecimalField(decimal_places=2, max_digits=3)),
                ("expected_graduation", models.IntegerField()),
            ],
            options={
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["id", "last_name"], name="schooldata__id_a23757_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "date_of_birth__lt",
                                django.db.models.functions.datetime.Now(),
                            )
                        ),
                        name="dob_in_past",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "expected_graduation__gte",
                                django.db.models.functions.datetime.Now(),
                            )
                        ),
                        name="expected_graduation_not_in_past",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "Introduction"),
                            (2, "Foundation"),
                            (3, "Advanced"),
                            (4, "Extracurricular"),
                        ],
                        default=0,
                    ),
                ),
                ("description", models.TextField()),
                ("students", models.ManyToManyField(to="schooldata.student")),
                ("teachers", models.ManyToManyField(to="schooldata.teacher")),
            ],
            options={
                "ordering": ["name", "-level"],
                "unique_together": {("name", "level")},
            },
        ),
        migrations.CreateModel(
            name="Annotations",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("note", models.TextField(default="")),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schooldata.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-student"],
                "indexes": [
                    models.Index(
                        fields=["student"], name="schooldata__student_ef44e8_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("duration", models.DurationField()),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "class_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schooldata.classroom",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schooldata.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schooldata.teacher",
                    ),
                ),
            ],
            options={
                "ordering": ["class_room", "-date", "time"],
                "indexes": [
                    models.Index(
                        fields=["class_room", "date"],
                        name="schooldata__class_r_ecc629_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("duration__gte", datetime.timedelta(0)),
                            ("duration__lte", datetime.timedelta(seconds=10800)),
                        ),
                        name="duration_within_range",
                    )
                ],
                "unique_together": {("class_room", "date", "time")},
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.IntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "D"),
                            (2, "C"),
                            (3, "B"),
                            (4, "A"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "Low"),
                            (2, "Medium"),
                            (3, "High"),
                        ],
                        default=0,
                    ),
                ),
                ("date_given", models.DateField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schooldata.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schooldata.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schooldata.teacher",
                    ),
                ),
            ],
            options={
                "ordering": ["subject", "teacher", "student"],
                "indexes": [
                    models.Index(
                        fields=["subject"], name="schooldata__subject_b64c33_idx"
                    )
                ],
            },
        ),
    ]
