# Generated by Django 5.1.5 on 2025-02-03 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schooldata", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="student",
            name="expected_graduation_not_in_past",
        ),
    ]
