# Generated by Django 5.1.5 on 2025-02-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schooldata", "0003_remove_student_dob_in_past"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="students",
            field=models.ManyToManyField(
                related_name="subjects", to="schooldata.student"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="teachers",
            field=models.ManyToManyField(
                related_name="teachers", to="schooldata.teacher"
            ),
        ),
    ]
