# Generated by Django 5.1.5 on 2025-02-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schooldata", "0004_alter_subject_students_alter_subject_teachers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="teachers",
            field=models.ManyToManyField(
                related_name="subjects", to="schooldata.teacher"
            ),
        ),
    ]
