# Generated by Django 5.1.5 on 2025-02-05 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schooldata", "0005_alter_subject_teachers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grade",
            options={
                "ordering": ["subject", "teacher", "student"],
                "permissions": [("add_new_grade", "Can add a grade")],
            },
        ),
    ]
