# Generated by Django 5.1.5 on 2025-02-05 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schooldata", "0006_alter_grade_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grade",
            options={"ordering": ["subject", "teacher", "student"]},
        ),
    ]
