# Generated by Django 5.1.5 on 2025-02-05 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schooldata", "0007_alter_grade_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="subjects",
            field=models.ManyToManyField(
                related_name="teachers_of_subject", to="schooldata.subject"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="teachers",
            field=models.ManyToManyField(
                related_name="subjects_taught", to="schooldata.teacher"
            ),
        ),
    ]
