# Generated by Django 5.1.5 on 2025-02-05 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schooldata", "0008_teacher_subjects_teacher_user_alter_subject_teachers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="user",
        ),
    ]
