# Generated by Django 5.1.5 on 2025-02-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schooldata", "0009_remove_teacher_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="regular",
            field=models.BooleanField(default=True),
        ),
    ]
