# Generated by Django 5.1.5 on 2025-02-09 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schooldata", "0015_alter_teacher_user"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="schedule",
            name="duration_within_range",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="duration",
        ),
    ]
