# Generated by Django 5.1.5 on 2025-02-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schooldata", "0016_remove_schedule_duration_within_range_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="regular",
        ),
        migrations.AddField(
            model_name="schedule",
            name="recurring",
            field=models.BooleanField(default=False),
        ),
    ]
