# Generated by Django 5.1.5 on 2025-02-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schooldata", "0017_remove_subject_regular_schedule_recurring"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
